title: Apartment 3D
description: Documentation for apartment 3D, Rosa de los Vientos, Isla Plana
theme: just-the-docs

url: https://domantax.github.io/spain-3d-en-docs

permalink: /:title

callouts:
  note:
    title: Note
    color: yellow